/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
        colors: {
        "newsmast-light-grey": "#F8F8F8",
        "newsmast-very-light-blue": "#F2F7FC",
        "newsmast-light-blue": "#F3F6FF",
        "newsmast-blue-grey": "#DCE0EB",
        "newsmast-grey": "#96A6C2",
        "newsmast-grey-2": "#9299A3",
        "newsmast-grey-3": "#6D7587",
        "newsmast-dark-blue": "#364663",
        "newsmast-black-lighter": "#2C2D2F",
        "newsmast-purple": "#735BF2",
        "newsmast-primary": "#EC6249",
        "newsmast-light-blue-2": "#4D9FFF",
        "newsmast-error": "#D02828",
        "newsmast-green": "#2DE1A0",
        "newsmast-tab-grey": "#F1F4F8",
        "newsmast-dark-grey": "#42454F",
        "newsmast-dark-light": "#ACB0B9",
        "newsmast-error-2": "#FF8C8C",
        "newsmast-warning": "#EC6249",
        "newmast-true": "#2de1a0",
        "newmast-border": "#DCE0EB",
        "newsmast-active": "#e33d26",
        "newsmast-hover": "#0288D1",
        "newsmast-light-blue-3": "#FF7C64",
        "newsmast-primary-2":"#D24A34",
        "newmast-amplifier":"#fff2f0",
        "newmast-border":"#0D0D0D",
        "newmast-black":"#F2F2F2",
        "mastodon":"#fbfcfe",
         "mastodon-button":"#dfe0e3",
         "mastodon-border":"#3e8c9f",
         "mastodon-fill":"#dce4e8",
         "newsmast-title-label":"#EC6D62",
         "pathwork-border":"#323542",
         "pathwork-label":"#626982"
      },
      fontSize: {
        sm: '0.8rem',
        base: '1rem',
        xl: '1.25rem',
        'sidebar-title':'11px',
        'community': '12px',
        'action': '13px',
        'default': '14px',
        'content': '15px',
        'count': '16px',
        'content-header': '17px',
        'heading': '18px',
        'max-heading': '19px',
        'sidebar':'20px',
        'select-heading': '22px',
        'auth': '24px',
        'app-title': '26px',
        '3xl': '1.953rem',
        '4xl': '2.441rem',
        '5xl': '3.052rem',
      },
      fontWeight: {
        thin: '100',
        hairline: '100',
        extralight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        'extra-bold': '800',
        black: '900',
      },
    },
  },
  plugins: [],
}